all:
  children:

    kubernetes:
      children:

        kubernetes-masters:
          hosts:
            kube-master-01:
               ansible_ssh_host: 172.17.8.101
               ansible_user: vagrant
               ansible_ssh_common_args: -o StrictHostKeyChecking=no
               ansible_ssh_private_key_file: ./.vagrant/machines/kube-master-01/virtualbox/private_key

        kubernetes-workers:
          hosts:
            kube-worker-01:
               ansible_ssh_host: 172.17.8.102
               ansible_user: vagrant
               ansible_ssh_common_args: -o StrictHostKeyChecking=no
               ansible_ssh_private_key_file: ./.vagrant/machines/kube-worker-01/virtualbox/private_key
