---
- name: Enable IP forwarding
  command: sysctl net.ipv4.ip_forward=1

- name: Enable /proc/sys/net/bridge/bridge-nf-call-iptables
  command: sysctl net.bridge.bridge-nf-call-iptables=1

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"

- name: Join to Kubernetes cluster
  shell: |
    kubeadm join \
                 --token {{ token }} \
                 {{ kube_master_address }}:6443 \
                 --discovery-token-unsafe-skip-ca-verification
  args:
    executable: /bin/bash

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
